In [1]:
!pip install Numpy

In [2]:
!pip install numpy

In [4]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in d:\anaconda\lib\site-packages (1.18.3)


In [5]:
import numpy as np

In [6]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [7]:
type(array_one)

numpy.ndarray

In [8]:
numbers=[20,30,40,50,60]
array_two = np.array(numbers)
array_two

array([20, 30, 40, 50, 60])

In [11]:
array_of_zeros=np.zeros([3,5])
array_of_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
array_of_ones=np.ones([3,5])
array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
array_of_ones=np.ones((3,5),dtype=np.int16)
array_of_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)